# Things to be covered

### From Day 1
- Git, github and gitpod
- python installation and venv
- Tools required for Data Science
- numpy
- pandas
- matplotlib
- sklearn


## Day 2

- ### Data Preprocessing
    - Scaling and Normalization
        - https://wellsr.com/python/data-scaling-and-normalization-with-python/
    - Encoding
        - only talk about one hot encoder and label encoder
        - https://medium.com/perspectivesondatascience/data-preprocessing-part-iv-categorical-encoding-e37599d0f34d
        
    - Train Test Split
    - Cross Validation
        - Outlier
        - Data Imbalance
        
- https://medium.com/analytics-vidhya/boston-house-price-prediction-using-machine-learning-ad3750a866cd#:~:text=Training%20Accuracy%3A%2099.9%25%20Accuracy.&text=From%20the%20Exploratory%20Data%20Analysis,performed%20better%20than%20Linear%20Regression.        
- ### Intro to machine learning
    - Machine learning algorithms
        - Linear Regression
            - https://realpython.com/train-test-split-python-data/
        - Decision Tree
            - don't work on it.
     - Performance Metrics
         - Accuracy 
             - 
         - Precision
         - Recall
         - F1 Score
         
         
- ## Tools:
    - sklearn

In [1]:
# Tools:
# numpy: pip install numpy
# pandas: pip install pandas
# matplotlib: pip install matplotlib
# sklearn: pip3 install -U scikit-learn


In [2]:
# exercise on numpy
import numpy

In [3]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

In [6]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [7]:
# dimensions in arrays
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [9]:
a.ndim, b.ndim, c.ndim, d.ndim

(0, 1, 2, 3)

In [11]:
# fetch elements
b

array([1, 2, 3, 4, 5])

In [16]:
# get the first element
b[0]

1

In [17]:
# get the last element
b[-1]

5

In [18]:
# inverse it
b[::-1]

array([5, 4, 3, 2, 1])